### ISSUE TITLE
Bugs when converting to/from RGB

### ISSUE THREAD

**Issue by Aloso** [ChevyRay/color_space#5]
I'm using this crate in [colo](https://github.com/Aloso/colo), and encountered a few bugs, because `Rgb` color channels are sometimes treated as values between 0 and 1, but should be treated as values between 0 and 255:

* [`Rgb::from_hex`](https://docs.rs/color_space/0.5.2/color_space/struct.Rgb.html#method.from_hex)
* [`Hsl::from_rgb`](https://docs.rs/color_space/0.5.2/color_space/trait.FromRgb.html#method.from_rgb-2)

These are the only cases I have found, but to be sure, there should be thorough tests.

**Comment by ChevyRay** [comment]
thanks for the report!
`Rgb::from_hex` is a pretty straightforward fix. looking into `Hsl::from_rgb` now.

**Comment by ChevyRay** [comment]
Okay, this should be fixed in [13ddcf](https://github.com/ChevyRay/color_space/commit/13ddcfc8bcfae9536afea8260832c547c58cca60), let me know if anything else is funky.

**Comment by ChevyRay** [comment]
Going to close, but I'll re-open if I somehow messed up the fix. If anyone is up for writing more thorough tests for all the conversions, I'd be super happy to accept that PR. Cheers!

**Comment by Aloso** [comment]
@ChevyRay  Thanks for fixing this so quickly!
